### ISSUE TITLE
Switching to one-time donation makes other amount box disappear

### ISSUE THREAD

**Issue by larssg-wildsight** [adixon/ca.civicrm.contributionrecur#5]
Switching from monthly donations to one-time donation using the recur/non-recur JS switcher causes the other amount box to disappear. Consequently, the user can't enter an other donation amount for one-time donations (though the other radio select is still visible. Confirmed in Chrome and Safari.

![Screen Shot 2020-08-05 at 5 27 20 PM](https://user-images.githubusercontent.com/25517556/89473797-0847f100-d741-11ea-8ca6-0e02c6e85e7d.png)

![Screen Shot 2020-08-05 at 5 27 29 PM](https://user-images.githubusercontent.com/25517556/89473793-0716c400-d741-11ea-8448-722d120217fd.png)

It looks like the JS is trying to show another other amount field (.other_one_time_amount-section), but that field doesn't exist on my pages.

**Comment by adixon** [comment]
Thanks for this, will review.

**Comment by adixon** [comment]
Ah, yes! That is in fact a sort of a feature. The issue arises because you don't want an other amount that got put in the one-time entry getting used if they switch over to recurring (I had a complaint from a client about this). Or maybe it was because they wanted clearer labelling ...

The solution is an undocumented hack, visible in this example:

https://secure.fairvote.ca/en/civicrm/contribute/transact?reset=1&id=9

The hack was to create separate other amount fields for monthly and one-time options in a price set. I suspect the js is a terrible hack to support whatever classes got generated in my specific example.

Patches welcome ...

**Comment by larssg-wildsight** [comment]
OK, that makes sense. It does look like the JS is there to support showing and hiding the two other amount fields and the two different selects with different amount options. 

Could you share a screenshot of the price set setup that makes this all work? I could probably reverse engineer it, but would be easier to see it directly.

For a path, would it make sense to just add some checks if those other fields exist and if not, ignore all the showing and hiding?
Then I could maybe add some documentation about how to set up a price set to achieve what happens in your example.

**Comment by adixon** [comment]
Sorry for the delay in reply. Here's the key lines in the js: https://github.com/adixon/ca.civicrm.contributionrecur/blob/d0ca08a992b7a706cb3de366ab4f9fd2309d148f/js/donation.js#L39

The short answer is, you have to label the price fields so that those selectors work properly. 

This is now documented here: 

https://github.com/adixon/ca.civicrm.contributionrecur/blob/master/README.md#provide-a-js-based-recurringnon-recurring-switcher
